### PR TITLE
325-remove-establishmentid-on-logout: done

### PR DESCRIPTION
**Pull request by adamfaryna**
https://trello.com/c/9Ao5YaUk

### CODE REVIEW

**Comment by wozzer72** [comment]
The code changes are clear. We have however introduced a dependency an additional dependency(Establishment service) into the header component. I understand Angular support RxJS. There must be a better to implement this without such as rigid (brittle) dependency.

Something like the Establishment service listening for notification from the AuthService there is a logout activity.
Or to simplify the implementation, the AuthService and Establishment service having a dependency. But to make the header dependent on Establishment service does not make a lot of sense here.

And finally, the destination for this change is identified as develop. It is not clear from the Trello task of this PR what the priority of the work is. Need clearer direction on which release this change is being approved for.

**Comment by adamfaryna** [comment]
[Home postcode #152](https://trello.com/c/SPakfIMh/44-home-postcode-152)

**Comment by adamfaryna** [comment]
> The code changes are clear. We have however introduced a dependency an additional dependency(Establishment service) into the header component. I understand Angular support RxJS. There must be a better to implement this without such as rigid (brittle) dependency.
> 
> Something like the Establishment service listening for notification from the AuthService there is a logout activity.
> Or to simplify the implementation, the AuthService and Establishment service having a dependency. But to make the header dependent on Establishment service does not make a lot of sense here.
> 
> And finally, the destination for this change is identified as develop. It is not clear from the Trello task of this PR what the priority of the work is. Need clearer direction on which release this change is being approved for.

We are still waiting for as refactoring of frontend code base by @denny13 as anticipated. The solution for mentioned problem was already addressed in https://github.com/NMDSdevopsServiceAdm/SopraSteria-SFC/pull/181, before this is approved we have to copy and paste the same common code between service files (related to setting headers and handling errors) or reuse existing code base.

Hopely entire code base will be cleared soon so these kind of workarounds wouldn't be necessary.

**Comment by wozzer72** [comment]
I'm not seeing how the interceptor, the goal of which is to ensure a reference set of data to initiate RESTful API calls can be used to decouple logout and establishment service, with the aim of deleting the establishment id from local storage. Logout and the removing of the local storage items is not an API call.

**Comment by adamfaryna** [comment]
I misunderstood your previous comment.

Yes, I don't like it either, it's compromise. I don't want to make EstablishmentService, nor AuthService dependent on one another. Subscribing to observers will create this kind of dependency, similar as just injecting one service into another.

The best solution would be to make AuthService emit logout event, than anyone interested would subscribe. I will try to refactor this solution to use JS custom events.

**Comment by adamfaryna** [comment]
[Remove establishmentId on logout](https://trello.com/c/9Ao5YaUk/325-remove-establishmentid-on-logout)

**Comment by wozzer72** [comment]
This has been superseeded by https://github.com/NMDSdevopsServiceAdm/SopraSteria-SFC/pull/257.

**Pull request closed without merging**
