### PR TITLE
Treat 400 erros as a valid response

### PR DESCRIPTION
**Pull request by tgreyuk**

### CODE REVIEW

**Comment by tgreyuk** [comment]
@omarCreativeDev it depends on what onValidateSuccess is. Technically the response has been validated successfully.

**Comment by omarCreativeDev** [comment]
> @omarCreativeDev it depends on what onValidateSuccess is. Technically the response has been validated successfully.

I hear you. Perhaps `onValidateSuccess` would be better named as `onValidateComplete`...?

**Comment by tgreyuk** [comment]
@omarCreativeDev yes onValidateComplete is good i have gone with that

**Comment by tgreyuk** [comment]
[(3) Bulk Upload - Passed Validation with Warnings](https://trello.com/c/UUgLf5iu/62-3-bulk-upload-passed-validation-with-warnings)

**Pull request merged**
