### PR TITLE
Changes for linux stack as per gov paas instruction

### PR DESCRIPTION
**Pull request by nasirmids**
Hello, quick PR for review; basically i have email from gov paas that they updating their linux stack so ask us to upgrade all apps before 6th May to use recommended linux stack to avoid any issues. below is the ticket with full detail.  

https://trello.com/c/zlYrPzGc

### CODE REVIEW

**Comment by nasirmids** [comment]
> I'm happy enough to approve only the change to dev, but the trello card needs more work to identify the impact and the steps necessary to demonstrate success for this change.
> 
> We don't make any changes to blue/green or staging until we know dev is meeting expectations.

@wozzer72   ofcourse nothing rollout to Staging/Onward until dev is stable. I have though need to update trello what would be the approach.  Basically the list of steps to test would be 

-  Browse the website, Do registration
-  Check login and saving few records
-  Feedback
-  Sesssion Timeout
- GA Analytics working
- Ask Ann to do Testing on Dev
- Ask Warren to test OnDemand Reporting 
- Ask Shakir to check Conduit connection

**Comment by nasirmids** [comment]
[Redeploy all Gov Paas hosted Environments due to changes in Gov Pass platform](https://trello.com/c/zlYrPzGc/573-redeploy-all-gov-paas-hosted-environments-due-to-changes-in-gov-pass-platform)

**Comment by ChazUK** [comment]
[When no staff records exist 'Orange banner' should take user into the skeleton record flow.](https://trello.com/c/VuhrMMUo/592-when-no-staff-records-exist-orange-banner-should-take-user-into-the-skeleton-record-flow)

**Comment by nasirmids** [comment]
> Approving the changes in the PR, but need team to agree before the changes are merged and deployed.

@wozzer72  Yes will have this discussed tomorrow. Thanks

**Pull request merged**
