### PR TITLE
Feature accessilibity issues

### PR DESCRIPTION
**Pull request by bwilson-ux**
Hi guys - I've created a feature branch to cover the accessibility issues raised from the audit.

There are a hefty amount of template changes in terms of structure based on the requirements and a couple of JS component changes - I am happy to revisit these given more time (only had 2 days to tackle these, apologies...)

### CODE REVIEW

**Comment by ChazUK** [comment]
Thanks for this Bryce, super happy that these issues are being fixed. I think we've got a session scheduled in for Thursday where you guys can run us over the changes.

**Comment by bwilson-ux** [comment]
All good - I have tried to follow current naming conventions etc where applicable and totally happy to revisit some of the styling I have added to follow the govuk BEM standards - was getting a little shorter on time at this point!

**Comment by omarCreativeDev** [comment]
Hey @bwilson-ux, this is excellent work and as charlie said will be good for you to go through this pr with us as its quite a big pr. also just noticed there's 2 files that are showing up with conflicts.

**Comment by bwilson-ux** [comment]
Resolving those as we speak :D would have done it already but the train wifi is tedious!!


Best regards,



[id:image001.png@01D36F5C.E98813C0]
Bryce Wilson
UI Consulting Manager
Sopra Steria | UK Design Team
+44 (0)7729 454633
bryce.wilson@soprasteria.com<mailto:bryce.wilson@soprasteria.com>

“Dude, suckin’ at something is the first step to being sorta good at something.” - Jake the Dog

Before printing, think about the environment.
The content of this message may be confidential, legally privileged and protected by law. Unauthorized use, copying or disclosure of any of it may be unlawful. If you are not the intended recipient please notify the sender and remove it from your system. While attachments to this e-mail are checked for viruses, we do not accept any liability for any damage sustained by viruses.

________________________________

**Comment by nasirmids** [comment]
@alleypa Hello i am not a front end person to review; kindly remove me Thanks

**Comment by ChazUK** [comment]
@bwilson-ux Are you going to be doing anymore changes to this branch? Also can you email the reports to me so I can create tickets for these issues.

**Comment by ChazUK** [comment]
Ok, I'm going to say that the development on this branch is now done as it's coming up to 10 days old 🎂, so that we can merge it. @bwilson-ux @alleypa please don't update this branch, and run any more fixes by me so we can put them in the proper areas.

**Comment by ChazUK** [comment]
All fixes within this branch have been split out to separate branches and linked to their respective tickets and merged.

Closing this PR.

**Pull request closed without merging**
