### PR TITLE
Adding Who should do bulk upload

### PR DESCRIPTION
**Pull request by g-m-taylor**
#### Tests
Does this PR include tests for the changes introduced?
- [ ] Yes
- [ ] No, I found it difficult to test
- [x] No, they are not required for this change

### CODE REVIEW

**Review by madeviv — CHANGES_REQUESTED** [review]
Same thing with the other pr. Folder structure has changed.

Also you've removed all the components from the page. How will we test it?

**Comment by g-m-taylor** [comment]
> Same thing with the other pr. Folder structure has changed.
> 
> Also you've removed all the components from the page. How will we test it?

Test what? The components were arn't using anymore?

**Comment by madeviv** [comment]
You've removed the components that allow you to do the uploading

**Comment by g-m-taylor** [comment]
> You've removed the components that allow you to do the uploading. How can we test changes with no BU components?
Am I missing something? 
Dont we have a ticket to redesign that component? Aka the outcome of the drop and drop spike.  Why would we test it before we actually do the work for that?  Also the component is still on the original bulk upload page.

**Comment by madeviv** [comment]
If you take a look at that component on my PR it might make a bit more sense. We're developing the new functionality in parallel with the existing functionality so there will be some duplication as we iterate. The new page should get it's own components as the needs arise to diverge from the existing functionality

**Review by aaron-russell — DISMISSED** [review]

**Comment by g-m-taylor** [comment]
> If you take a look at that component on my PR it might make a bit more sense. We're developing the new functionality in parallel with the existing functionality so there will be some duplication as we iterate. The new page should get it's own components as the needs arise to diverge from the existing functionality

surely its better to add those components in when the need arises rather than mix old and new components mish-mashed together...

**Review by madeviv — APPROVED** [review]

**Pull request merged**
