### PR TITLE
Create canChangePermissionsForSubsidiary and canChangeDataOwner permissions property.

### PR DESCRIPTION
**Pull request by rchitranshi**
…ssionsForSubsidiary and canChangeDataOwner

### CODE REVIEW

**Comment by rchitranshi** [comment]
[Update permissions](https://trello.com/c/qmNvbUsc/3-update-permissions)

**Comment by rchitranshi** [comment]
https://trello.com/c/qmNvbUsc

**Comment by Negi-Anurag** [comment]
Looks good to me.

**Comment by pjshumphreys** [comment]
Yep. Looks good to me also :+1

**Pull request merged**
