### PR TITLE
134-service-capacities-issue-removing-the-last-service-for-which-ther…

### PR DESCRIPTION
**Pull request by adamfaryna**
High priority!

### CODE REVIEW

**Comment by adamfaryna** [comment]
> I don't understand how the code changes made satisfy the two issues raised in the trello card. There are no comments on the card or in this PR or in the code to why things were changed and for what reason.
> 
> There is also no evidence on the card to show the two issues as fixed.

To understand what this change brings to the table, please have a look at entire context in the related file. If you have any questions, please add them to related hunk or line.

**Comment by wozzer72** [comment]
Still doesn't help. As the author of the change, I expect you to provide the rationalisation. As the reviewed of the change, I would expect to be given every piece of information possible to ensure a smooth and efficient review. As the reviewer of the change, I am not expected to second guess your intentions.

**Comment by adamfaryna** [comment]
> Still doesn't help. As the author of the change, I expect you to provide the rationalisation. As the reviewed of the change, I would expect to be given every piece of information possible to ensure a smooth and efficient review. As the reviewer of the change, I am not expected to second guess your intentions.

@wozzer72  as instructed, you are 2 clicks away from informations you asking for, just click "Files changed" -> "Raw" to see entire file (context) which this change impacts. Everything should be clear after. If you don't feel confident to review frontend code, please delegate it to frontend developer.

**Comment by wozzer72** [comment]
The feedback on this PR has not been addressed, and the change does not address the two observations against the original trello card: https://trello.com/c/DaF6aafY. This Pr and it's branch will be closed.

**Pull request closed without merging**
