### PR TITLE
Reformatting the input and reponse for starters, leavers and vacancies

### PR DESCRIPTION
**Pull request by wozzer72**
on endpoint `[POST] http://localhost:3000/api/establishment/479/jobs`, removed the prefix with "jobs":
```
{
	"leavers" : [
		{
			"title" : "Activities worker or co-ordinator",
			"total" : 999
		},
		{
			"jobId" : 10,
			"total" : 333
		}
	],
	"vacancies": "None",
	"starters": "Don't know"
}
```

and response is:
```
{
  "id": 479,
  "uid": "98a83eef-e1e1-49f3-89c5-b1287a3cc8dd",
  "name": "WOZiTech Cares Updated",
  "created": "2019-03-15T09:54:10.562Z",
  "updated": "2019-06-15T09:46:14.884Z",
  "updatedBy": "aylingw",
  "vacancies": "None",
  "totalVacancies": 0,
  "starters": "Don't know",
  "totalStarters": 0,
  "leavers": [
    {
      "jobId": 1,
      "title": "Activities worker or co-ordinator",
      "total": 999
    },
    {
      "jobId": 10,
      "title": "Care Worker",
      "total": 333
    }
  ],
  "totalLeavers": 1332
}
```
Note all properties are lowercase prefixed and the spelling correction on `totalVacancies`.

on endpoint `[GET] http://localhost:3000/api/establishment/479` and endpoint `[GET] http://localhost:3000/api/establishment/479/jobs` - both return the same output as above.

### CODE REVIEW

**Comment by ChazUK** [comment]
Updated the PR to include the changes for FE code

**Comment by wozzer72** [comment]
I've reviewed the frontend changes, and all looks good. Good to approve and deploy when ready.

**Comment by wozzer72** [comment]
Confirmation that updated integration tests are working
image

**Comment by wozzer72** [comment]
Whilst checking all existing integration tests, I picked up on a change previously made to registration when the main service id is incorrect. Have taken the opportunity to fix it here.

**Comment by alleypa** [comment]
[(1) Date error messages are all caps](https://trello.com/c/JBl6JpYW/115-1-date-error-messages-are-all-caps)

**Pull request merged**
